- name: users | velociraptor | Create user
  tags: dotfiles,velociraptor,ssh,ssh-keys,users
  user:
    name: velociraptor
    create_home: yes
    groups: users,{{ sudo_group }}
    state: present
    # password: "{{ ansible_sudo_pass }}"
    password: "{{ user_passwd }}"

- name: users | velociraptor | add public key
  tags: dotfiles,velociraptor,ssh,ssh-keys,users
  authorized_key:
    user: velociraptor
    key: "{{ item }}"
  with_file:
    - users/velociraptor/ssh/velociraptor_id_rsa.pub
    # - users/velociraptor/ssh/velociraptor_id_ed25519.pub

- name: users | velociraptor | add sudoers file
  tags: settings,velociraptor,sudo,system,users
  copy:
    src: users/sudoers_velociraptor
    dest: /etc/sudoers.d/velociraptor
    owner: root
    group: root
    mode: 0440